### ISSUE TITLE
It is failing, Which Node version are you using?? 

### ISSUE THREAD

**Issue by vpwhydonate** [vinaypuppal/cfw-prisma-template#1]
> node build.js

 > node_modules/@prisma/client/runtime/index.js:67:45: error: Could not resolve "async_hooks" (use "platform: 'node'" when building for node)
    67 │ var import_async_hooks = __toModule2(require("async_hooks"));
       ╵                                              ~~~~~~~~~~~~~

 > node_modules/@prisma/client/runtime/index.js:27241:25: error: Could not resolve "_http_common" (use "platform: 'node'" when building for node)
    27241 │     var common = require("_http_common");

**Comment by mangledbottles** [comment]
+1

**Comment by vinaypuppal** [comment]
Hey, sorry I missed this issue

With [wrangler](https://github.com/cloudflare/wrangler2) I guess this template is no longer required but there is a prisma client issue even with wrangler2 as mentioned here https://github.com/prisma/prisma/issues/13434#issuecomment-1135390668 so try it with wrangler2 once prisma client issue is fixed.

Closing this issue and will archive this template
